# Generated by Django 5.2.15 on 2026-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='solved_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
