# Generated by Django 5.2.15 on 2026-06-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_solved_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='solved_count',
        ),
    ]
