# Generated by Django 5.2.15 on 2026-06-19 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='input_description',
            new_name='examples',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='output_description',
        ),
    ]
