# Generated by Django 5.2.15 on 2026-06-24 11:16

import django.core.validators
from django.db import migrations, models


def keep_existing_problems_in_stdin_mode(apps, schema_editor):
    problem = apps.get_model("problems", "Problem")
    problem.objects.update(judge_mode="stdin")


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_input_description_problem_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='function_name',
            field=models.CharField(default='solve', max_length=100, validators=[django.core.validators.RegexValidator(message='Function name must be a valid Python identifier.', regex='^[A-Za-z_][A-Za-z0-9_]*$')]),
        ),
        migrations.AddField(
            model_name='problem',
            name='judge_mode',
            field=models.CharField(choices=[('stdin', 'Standard input'), ('function', 'Function')], default='function', max_length=16),
        ),
        migrations.AddField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(
            keep_existing_problems_in_stdin_mode,
            migrations.RunPython.noop,
        ),
    ]
