# Generated by Django 5.2.15 on 2026-06-24 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_function_name_problem_judge_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='judge_mode',
        ),
        migrations.AddField(
            model_name='problem',
            name='function_arguments',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Arguments must be comma-separated Python identifiers.', regex='^$|^[A-Za-z_][A-Za-z0-9_]*(,\\s*[A-Za-z_][A-Za-z0-9_]*)*$')]),
        ),
    ]
