# Generated by Django 5.2.15 on 2026-06-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_solved_progress(apps, schema_editor):
    submission = apps.get_model("submissions", "Submission")
    progress = apps.get_model("problems", "UserProblemProgress")
    seen = set()

    accepted_submissions = submission.objects.filter(status="accepted").order_by(
        "user_id",
        "problem_id",
        "created_at",
        "id",
    )

    for accepted in accepted_submissions.iterator():
        key = (accepted.user_id, accepted.problem_id)
        if key in seen:
            continue
        seen.add(key)

        record = progress.objects.create(
            user_id=accepted.user_id,
            problem_id=accepted.problem_id,
            first_accepted_submission_id=accepted.id,
        )
        solved_at = accepted.judged_at or accepted.created_at
        progress.objects.filter(pk=record.pk).update(solved_at=solved_at)


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_judge_mode_problem_function_arguments'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProblemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('first_accepted_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_accept_progress', to='submissions.submission')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-solved_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'problem'), name='unique_user_problem_progress')],
            },
        ),
        migrations.RunPython(backfill_solved_progress, migrations.RunPython.noop),
    ]
